[package]
name = "tcpdumb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = { version = "0.31.0", features = ["std"] }
tui = "0.19.0"
crossterm = "0.23.2"
